apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    #    - 192.168.0.61-192.168.0.70
    - fc00:f853:ccd:e793::b - fc00:f853:ccd:e793::ff
    # - 172.18.255.200 - 172.18.255.250
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool