apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - uri:
            exact: /hello
      rewrite:
        uri: "/"
      route:
        - destination:
            host: hello-service.hello.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /hello/
      route:
        - destination:
            host: hello-service.hello.svc.cluster.local
            port:
              number: 80
